# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [1]:
from scipy import stats
import numpy as np

In [2]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])
#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [5]:
from scipy import stats
import pandas as pd
import numpy as np
true_mu = 0
results =stats.ttest_1samp(GPU1, true_mu)
alpha = 0.05
if (results[0] < 0) & (results[1]/2 < alpha):
    print ("reject null hypothesis,accept Alternate Hypothesis")#mean is not equal to zero
else:
    print ("accept null hypothesis") #mean is equal to zero

accept null hypothesis


## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [4]:
from scipy.stats import ttest_rel
stat,p=ttest_rel(GPU1,GPU2)
print('statistics=%.3f,p=%.3f'%(stat,p))
alpha = 0.05
if p > alpha:
	print('Accept null hypothesis that there is no significant difference between data sets.')
else:
	print('Reject the null hypothesis and accept Alternate hypothesis that there is a significant difference in data sets')

statistics=-2.542,p=0.023
Reject the null hypothesis and accept Alternate hypothesis that there is a significant difference in data sets


## Question 3

He is trying a third GPU - GPU3.

In [6]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])
#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [7]:
from scipy.stats import ttest_rel
stat,p=ttest_rel(GPU1,GPU3)
print('statistics=%.3f,p=%.3f'%(stat,p))
alpha = 0.05
if p > alpha:
	print('Accept null hypothesis that there is no significant difference between data sets.')
else:
	print('Reject the null hypothesis and accept Alternate hypothesis that there is a significant difference in data sets')

statistics=-1.585,p=0.135
Accept null hypothesis that there is no significant difference between data sets.


## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [25]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

In [26]:
from scipy.stats import levene
levene(e1,e2,e3)

LeveneResult(statistic=2.6741725711150446, pvalue=0.12259792666001798)

## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [28]:
from numpy.random import seed
from numpy.random import randn
from scipy.stats import f_oneway
stat, p = f_oneway(GPU1, GPU3)
print('Statistics=%.3f, p=%.3f' % (stat, p))
alpha = 0.05
if p > alpha:
	print('Same distributions (Accept null hypothesis H0)')
else:
	print('Different distributions (reject H0)')

Statistics=2.247, p=0.145
Same distributions (Accept null hypothesis H0)


## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

TypeI Error - TypeI Error is when you reject a null hypothesis which is actually TRUE in the population(False-positive). TypeII Error - TypeII error is when you fail to reject a null hypothesis which is actually false in the populations( False - Negative)

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:
H0 = 4.5 mins ( Null Hypothesis)
H1== 4.5 mins(H1<4.5 or H1> 4.5 mins is Alternate Hypothesis)
alpha=0.05, if p value<alpha reject null hypothesis and accept alternate hypothesis.
if p value>alpha, accept null hypothesis.


## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [29]:
import numpy as np

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [32]:
from scipy import stats
stats.chi2_contingency(dice)
chi2_stat, p_val, dof, ex = stats.chi2_contingency(dice)
print("Chi2 Stat")
print(chi2_stat)
print("\n")
print("Degrees of Freedom")
print(dof)
print("\n")
print("P-Value")
print(p_val)
print("\n")
print("Contingency Table")
print(ex)

Chi2 Stat
23.315671914716496


Degrees of Freedom
15


P-Value
0.07766367301496693


Contingency Table
[[ 5.57419355  8.20645161  5.57419355  4.64516129]
 [ 6.50322581  9.57419355  6.50322581  5.41935484]
 [ 6.73548387  9.91612903  6.73548387  5.61290323]
 [ 6.96774194 10.25806452  6.96774194  5.80645161]
 [ 5.34193548  7.86451613  5.34193548  4.4516129 ]
 [ 4.87741935  7.18064516  4.87741935  4.06451613]]


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [69]:
import scipy
from scipy import stats
import numpy as np
import pandas as pd
stats.zscore(dice)
p_value = scipy.stats.norm.pdf(abs(zscore))
print ("zscore",zscore)
print("p_value",p_value)
np.mean(p_value)

zscore [[-0.46291005 -0.18884739 -1.83711731  1.44115338]
 [ 1.38873015 -0.64208114  1.22474487  0.        ]
 [ 0.9258201   0.7176201   0.61237244 -1.44115338]
 [-0.9258201   1.62408759  0.61237244 -0.96076892]
 [-1.38873015  0.03776948  0.          0.        ]
 [ 0.46291005 -1.54854863 -0.61237244  0.96076892]]
p_value [[0.35840868 0.39189152 0.0737969  0.14122512]
 [0.15209891 0.32462889 0.18844699 0.39894228]
 [0.25988658 0.30837835 0.33073477 0.14122512]
 [0.25988658 0.1066963  0.33073477 0.25145858]
 [0.15209891 0.39865783 0.39894228 0.39894228]
 [0.35840868 0.12027915 0.33073477 0.25145858]]


0.2678317841904247

## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [8]:
import scipy
from scipy import stats
import numpy as np
import pandas as pd
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [9]:
D  = after - before
import  scipy.stats  as stats  
t_statistic, p_value  =  stats.ttest_1samp(D, 0)
print(t_statistic)
print(p_value)

-3.7218399705602927
0.00022028110542044306


In [ ]:
# pvalue is very less which means drug has worked wonderfully on the patients 