In [204]:
# Import important library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

### Q1 Read the input file and check the data dimension

In [205]:
#Read input file and understand the data
# "default" is my dependent variable

In [206]:
df=pd.read_csv("german_credit.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
default                       1000 non-null int64
account_check_status          1000 non-null object
duration_in_month             1000 non-null int64
credit_history                1000 non-null object
purpose                       1000 non-null object
credit_amount                 1000 non-null int64
savings                       1000 non-null object
present_emp_since             1000 non-null object
installment_as_income_perc    1000 non-null int64
personal_status_sex           1000 non-null object
other_debtors                 1000 non-null object
present_res_since             1000 non-null int64
property                      1000 non-null object
age                           1000 non-null int64
other_installment_plans       1000 non-null object
housing                       1000 non-null object
credits_this_bank             1000 non-null int64
job                           1000

In [207]:
df.describe()

default  duration_in_month  credit_amount  \
count  1000.000000        1000.000000    1000.000000   
mean      0.300000          20.903000    3271.258000   
std       0.458487          12.058814    2822.736876   
min       0.000000           4.000000     250.000000   
25%       0.000000          12.000000    1365.500000   
50%       0.000000          18.000000    2319.500000   
75%       1.000000          24.000000    3972.250000   
max       1.000000          72.000000   18424.000000   

       installment_as_income_perc  present_res_since          age  \
count                 1000.000000        1000.000000  1000.000000   
mean                     2.973000           2.845000    35.546000   
std                      1.118715           1.103718    11.375469   
min                      1.000000           1.000000    19.000000   
25%                      2.000000           2.000000    27.000000   
50%                      3.000000           3.000000    33.000000   
75%                      4.000000           4.000000    42.000000   
max                      4.000000           4.000000    75.000000   

       credits_this_bank  people_under_maintenance  
count        1000.000000               1000.000000  
mean            1.407000                  1.155000  
std             0.577654                  0.362086  
min             1.000000                  1.000000  
25%             1.000000                  1.000000  
50%             1.000000                  1.000000  
75%             2.000000                  1.000000  
max             4.000000                  2.000000

In [208]:
# Lets build a Ensemble model but need to modify the dataset first

### Q2.Prepare the model data by converting non-numeric to dummy ( 1 Marks)
##### Hint: Use get_dummies

In [209]:
# Print Shape of model data
df.shape

(1000, 21)

In [210]:
dummies = pd.get_dummies(df["credit_history"])#.str.get_dummies(" ")
df=pd.concat([df,dummies],axis=1)
dummy=pd.get_dummies(df["account_check_status"])
df=pd.concat([df,dummy],axis=1)
dum1=pd.get_dummies(df["personal_status_sex"])
df=pd.concat([df,dum1],axis=1)
dum2=pd.get_dummies(df["housing"])
df=pd.concat([df,dum2],axis=1)
dum3=pd.get_dummies(df["other_installment_plans"])
df=pd.concat([df,dum3],axis=1)
dum5=pd.get_dummies(df["savings"])
df=pd.concat([df,dum5],axis=1)
dum6=pd.get_dummies(df["job"])
df=pd.concat([df,dum6],axis=1)
dum7=pd.get_dummies(df['foreign_worker'])
df=pd.concat([df,dum7],axis=1)
df=df.drop(['personal_status_sex','housing','telephone','credit_history','foreign_worker','job','other_installment_plans','account_check_status','savings','purpose','present_emp_since','property','other_debtors','present_res_since'],axis=1)
df.head(5)

default  duration_in_month  credit_amount  installment_as_income_perc  age  \
0        0                  6           1169                           4   67   
1        1                 48           5951                           2   22   
2        0                 12           2096                           2   49   
3        0                 42           7882                           2   45   
4        1                 24           4870                           3   53   

   credits_this_bank  people_under_maintenance  \
0                  2                         1   
1                  1                         1   
2                  1                         2   
3                  1                         2   
4                  2                         2   

   all credits at this bank paid back duly  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   

   critical account/ other credits existing (not at this bank)  \
0                                                  1             
1                                                  0             
2                                                  1             
3                                                  0             
4                                                  0             

   delay in paying off in the past  ...  ... < 100 DM  100 <= ... < 500 DM  \
0                                0  ...             0                    0   
1                                0  ...             1                    0   
2                                0  ...             1                    0   
3                                0  ...             1                    0   
4                                1  ...             1                    0   

   500 <= ... < 1000 DM   unknown/ no savings account  \
0                      0                            1   
1                      0                            0   
2                      0                            0   
3                      0                            0   
4                      0                            0   

   management/ self-employed/ highly qualified employee/ officer  \
0                                                  0               
1                                                  0               
2                                                  0               
3                                                  0               
4                                                  0               

   skilled employee / official  unemployed/ unskilled - non-resident  \
0                            1                                     0   
1                            1                                     0   
2                            0                                     0   
3                            1                                     0   
4                            1                                     0   

   unskilled - resident  no  yes  
0                     0   0    1  
1                     0   0    1  
2                     1   0    1  
3                     0   0    1  
4                     0   0    1  

[5 rows x 37 columns]

### Check for highly correlated variables but don't required any treatment for this use case

In [219]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 37 columns):
default                                                          1000 non-null int64
duration_in_month                                                1000 non-null int64
credit_amount                                                    1000 non-null int64
installment_as_income_perc                                       1000 non-null int64
age                                                              1000 non-null int64
credits_this_bank                                                1000 non-null int64
people_under_maintenance                                         1000 non-null int64
all credits at this bank paid back duly                          1000 non-null uint8
critical account/ other credits existing (not at this bank)      1000 non-null uint8
delay in paying off in the past                                  1000 non-null uint8
existing credits paid back duly till now    

In [ ]:
#male : divorced/separated,male : married/widowed,male : single can be clubbed into just'male'
'all credits at this bank paid back duly', 'existing credits paid back duly till now' can be clubbed

### Q3 Split Train/Test data 70:30 ratio( 1 Marks)
##### Hint:from sklearn.model_selection import train_test_split

In [220]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size = 0.3)

### Q4 Build Random Forest Model( 2 Marks)
#### Hint:from sklearn.ensemble import RandomForestClassifier using n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999

In [222]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=500,n_jobs=2,criterion="entropy",random_state=9999,max_leaf_nodes=15)
clf

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=15,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=2,
                       oob_score=False, random_state=9999, verbose=0,
                       warm_start=False)

### Q5 Calculate Confusion Matrix and Accuracy score (1 Marks)
##### Hint: Use confusion_matrix and accuracy_score

In [243]:
X=df.drop(['default'], axis=1)
Y=df['default']
X_train, X_test,Y_train,Y_test = train_test_split(X,Y, test_size =0.2342,random_state=0)
X_train.shape,X_test.shape
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import model_selection
model=RandomForestClassifier()
model= model.fit(X_train, Y_train)
prediction=model.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, prediction)

0.7148936170212766

In [244]:
prediction

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [245]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test, prediction)
print(confusion_matrix)

[[145  19]
 [ 48  23]]


### Q6 Show the list of the features importance( 1 Marks)

In [ ]:
#credit_amount - how big or small the credit amount is necessary to consider
#installment_as_income_perc - this can help understand if the person can easily pay off the amount or if its difficult
#delay in paying off in the past - helps in understand if the person is a usual defaulter
#duration_in_month - helps understand the credit amount is due for how many months/days
#unemployed/unskilled- non-resident - there are higher chances he may not pay off the credit amount
#unknown/no savings account - need to clarify who are these customers 

### Q7 K-fold cross-validation( 2 Marks)
##### k-fold cross validation( without stratification)
##### Usually k is set as 10-20 in practical settings, depends on data set size

In [234]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [303]:
# Use below values
num_folds = 10
seed = 77

In [214]:
#Validate the Random Forest model build above using k fold

In [321]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVR
kf = KFold(n_splits =10, shuffle = True, random_state = 77)
scores = []
best_svr = SVR(kernel='rbf')
best_svr.fit(X_train, Y_train)
scores.append(best_svr.score(X_test, Y_test))

In [215]:
#Calculate Mean score

In [322]:
print(np.mean(scores))

-0.06662156614648973


In [216]:
# Calculate score standard deviation using std()

In [323]:
print(np.std(scores))

0.0


# Q8 Build Ada boosting model, check the accuracy, and print confusion matrix ( 1 Marks)

In [246]:
from sklearn.ensemble import AdaBoostClassifier
model=AdaBoostClassifier()
model= model.fit(X_train, Y_train)
prediction=model.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, prediction)

0.774468085106383

In [247]:
prediction

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [248]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test, prediction)
print(confusion_matrix)

[[143  21]
 [ 32  39]]


# Q9. Build Gradient boosting model, check the accuracy, and print confusion matrix ( 1 Marks)
percentage of correct predictions and Calculate sensitivity (or True Positive Rate or Recall) and Precision.
( 1 Marks)

In [252]:
from sklearn.ensemble import GradientBoostingClassifier
model=GradientBoostingClassifier()
model= model.fit(X_train, Y_train)
prediction=model.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, prediction)

0.7702127659574468

In [253]:
prediction

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [254]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test, prediction)
print(confusion_matrix)

[[146  18]
 [ 36  35]]


### Bootstrapping ( Bonus)
##### Given a dataset of size n, a bootstrap sample is created by sampling n instances uniformly from the data (with/without replacement)
##### Create a model with each bootstrap sample and validate it with the test set
##### Final result is calculated by averaging the accuracy of models

In [299]:
# Number of iterations for bootstrapping
bootstrap_iteration = 10
accuracy = []

In [300]:
from sklearn.utils import resample
from sklearn.metrics import accuracy_score

for i in range(bootstrap_iteration):
    X_, Y_ = resample(X_train, Y_train)
    rfm=model.fit(X_, Y_)
    y_pred = rfm.predict(X_test)
    
    acc = accuracy_score(y_pred, Y_test)
    accuracy.append(acc)

In [301]:
accuracy = np.array(accuracy)
print('Accuracy Score')
print('Avearge: ', accuracy.mean())
print('Standard deviation: ', accuracy.std())

Accuracy Score
Avearge:  0.7544680851063829
Standard deviation:  0.012630486876302851


In [ ]:
# Adaboost model is the best model with highest accuracy 